/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 23
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 18
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_source_file_token1 = 1,
  anon_sym_LF = 2,
  anon_sym_DASH_DASH_DASH = 3,
  sym_filename = 4,
  sym_progress = 5,
  sym_language = 6,
  aux_sym_line_num_token1 = 7,
  aux_sym_line_num_token2 = 8,
  sym_code = 9,
  sym_source_file = 10,
  sym_change = 11,
  sym_header = 12,
  sym_body = 13,
  sym_line = 14,
  sym_line_num = 15,
  aux_sym_source_file_repeat1 = 16,
  aux_sym_body_repeat1 = 17,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_source_file_token1] = "source_file_token1",
  [anon_sym_LF] = "\n",
  [anon_sym_DASH_DASH_DASH] = " --- ",
  [sym_filename] = "filename",
  [sym_progress] = "progress",
  [sym_language] = "language",
  [aux_sym_line_num_token1] = "line_num_token1",
  [aux_sym_line_num_token2] = "line_num_token2",
  [sym_code] = "code",
  [sym_source_file] = "source_file",
  [sym_change] = "change",
  [sym_header] = "header",
  [sym_body] = "body",
  [sym_line] = "line",
  [sym_line_num] = "line_num",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_source_file_token1] = aux_sym_source_file_token1,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_DASH_DASH_DASH] = anon_sym_DASH_DASH_DASH,
  [sym_filename] = sym_filename,
  [sym_progress] = sym_progress,
  [sym_language] = sym_language,
  [aux_sym_line_num_token1] = aux_sym_line_num_token1,
  [aux_sym_line_num_token2] = aux_sym_line_num_token2,
  [sym_code] = sym_code,
  [sym_source_file] = sym_source_file,
  [sym_change] = sym_change,
  [sym_header] = sym_header,
  [sym_body] = sym_body,
  [sym_line] = sym_line,
  [sym_line_num] = sym_line_num,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_filename] = {
    .visible = true,
    .named = true,
  },
  [sym_progress] = {
    .visible = true,
    .named = true,
  },
  [sym_language] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_line_num_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_line_num_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_code] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_change] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym_line_num] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == ' ') ADVANCE(1);
      if (lookahead == '.') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(18);
      if (('-' <= lookahead && lookahead <= '/') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(2);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '.') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(2);
      if (lookahead == '.') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(21);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_source_file_token1);
      if (lookahead == '\n') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_source_file_token1);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == ' ') ADVANCE(2);
      if (lookahead == '.') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_DASH);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_filename);
      if (lookahead == ' ') ADVANCE(24);
      if (lookahead == '.') ADVANCE(15);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_filename);
      if (lookahead == ' ') ADVANCE(22);
      if (lookahead == '/') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_filename);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('-' <= lookahead && lookahead <= '/') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_filename);
      if (('-' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_filename);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_progress);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_language);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_line_num_token1);
      if (lookahead == ' ') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_line_num_token1);
      if (lookahead == ' ') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_line_num_token2);
      if (lookahead == ' ') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_line_num_token2);
      if (lookahead == ' ') ADVANCE(24);
      if (lookahead == '.') ADVANCE(25);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 9},
  [2] = {.lex_state = 12},
  [3] = {.lex_state = 12},
  [4] = {.lex_state = 12},
  [5] = {.lex_state = 9},
  [6] = {.lex_state = 9},
  [7] = {.lex_state = 12},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 9},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 11},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 11},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0, .external_lex_state = 1},
  [18] = {.lex_state = 0, .external_lex_state = 1},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_DASH_DASH_DASH] = ACTIONS(1),
    [sym_filename] = ACTIONS(1),
    [sym_progress] = ACTIONS(1),
    [sym_language] = ACTIONS(1),
    [aux_sym_line_num_token1] = ACTIONS(1),
    [aux_sym_line_num_token2] = ACTIONS(1),
    [sym_code] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(10),
    [sym_change] = STATE(13),
    [sym_header] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_filename] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    STATE(3), 1,
      aux_sym_body_repeat1,
    STATE(15), 1,
      sym_body,
    STATE(18), 1,
      sym_line_num,
    STATE(20), 1,
      sym_line,
    ACTIONS(7), 2,
      aux_sym_line_num_token1,
      aux_sym_line_num_token2,
  [17] = 5,
    ACTIONS(9), 1,
      aux_sym_source_file_token1,
    STATE(4), 1,
      aux_sym_body_repeat1,
    STATE(18), 1,
      sym_line_num,
    STATE(20), 1,
      sym_line,
    ACTIONS(7), 2,
      aux_sym_line_num_token1,
      aux_sym_line_num_token2,
  [34] = 5,
    ACTIONS(11), 1,
      aux_sym_source_file_token1,
    STATE(4), 1,
      aux_sym_body_repeat1,
    STATE(18), 1,
      sym_line_num,
    STATE(20), 1,
      sym_line,
    ACTIONS(13), 2,
      aux_sym_line_num_token1,
      aux_sym_line_num_token2,
  [51] = 5,
    ACTIONS(5), 1,
      sym_filename,
    ACTIONS(16), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    STATE(11), 1,
      sym_header,
    STATE(13), 1,
      sym_change,
  [67] = 5,
    ACTIONS(18), 1,
      ts_builtin_sym_end,
    ACTIONS(20), 1,
      sym_filename,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    STATE(11), 1,
      sym_header,
    STATE(13), 1,
      sym_change,
  [83] = 2,
    ACTIONS(11), 1,
      aux_sym_source_file_token1,
    ACTIONS(23), 2,
      aux_sym_line_num_token1,
      aux_sym_line_num_token2,
  [91] = 2,
    ACTIONS(25), 1,
      sym_progress,
    ACTIONS(27), 1,
      sym_language,
  [98] = 1,
    ACTIONS(18), 2,
      ts_builtin_sym_end,
      sym_filename,
  [103] = 1,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
  [107] = 1,
    ACTIONS(31), 1,
      anon_sym_LF,
  [111] = 1,
    ACTIONS(33), 1,
      anon_sym_DASH_DASH_DASH,
  [115] = 1,
    ACTIONS(35), 1,
      aux_sym_source_file_token1,
  [119] = 1,
    ACTIONS(37), 1,
      anon_sym_DASH_DASH_DASH,
  [123] = 1,
    ACTIONS(39), 1,
      aux_sym_source_file_token1,
  [127] = 1,
    ACTIONS(41), 1,
      anon_sym_LF,
  [131] = 1,
    ACTIONS(43), 1,
      sym_code,
  [135] = 1,
    ACTIONS(45), 1,
      sym_code,
  [139] = 1,
    ACTIONS(47), 1,
      sym_language,
  [143] = 1,
    ACTIONS(49), 1,
      anon_sym_LF,
  [147] = 1,
    ACTIONS(51), 1,
      anon_sym_LF,
  [151] = 1,
    ACTIONS(53), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 17,
  [SMALL_STATE(4)] = 34,
  [SMALL_STATE(5)] = 51,
  [SMALL_STATE(6)] = 67,
  [SMALL_STATE(7)] = 83,
  [SMALL_STATE(8)] = 91,
  [SMALL_STATE(9)] = 98,
  [SMALL_STATE(10)] = 103,
  [SMALL_STATE(11)] = 107,
  [SMALL_STATE(12)] = 111,
  [SMALL_STATE(13)] = 115,
  [SMALL_STATE(14)] = 119,
  [SMALL_STATE(15)] = 123,
  [SMALL_STATE(16)] = 127,
  [SMALL_STATE(17)] = 131,
  [SMALL_STATE(18)] = 135,
  [SMALL_STATE(19)] = 139,
  [SMALL_STATE(20)] = 143,
  [SMALL_STATE(21)] = 147,
  [SMALL_STATE(22)] = 151,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [9] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [16] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [18] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [29] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_change, 3, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 3, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_num, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 5, 0, 0),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_code = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_code] = sym_code,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_code] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_difft_external_scanner_create(void);
void tree_sitter_difft_external_scanner_destroy(void *);
bool tree_sitter_difft_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_difft_external_scanner_serialize(void *, char *);
void tree_sitter_difft_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_difft(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_difft_external_scanner_create,
      tree_sitter_difft_external_scanner_destroy,
      tree_sitter_difft_external_scanner_scan,
      tree_sitter_difft_external_scanner_serialize,
      tree_sitter_difft_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
